public_gsheets_url = "https://docs.google.com/spreadsheets/d/1SWjRnvDbzD6TT2_6uEevU63Nujktl9BsJni6VFOqrgk/edit#gid=0"
[mysql]
host = "localhost"
port = 3306
database = "webframework"
user = "root"
password = "admin"